name: wellness_companion
description: Wellness companion app (SIH26094 - Team Voltix)
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  record: ^5.1.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
